### ISSUE TITLE
Multiple Monitor support

### ISSUE THREAD

**Issue by MikeShiner** [wsdfhjxc/virtual-desktop-bar#13]
This applet works well but I would really like to see a "Only show desktops on the current screen". I'm running i3wm with KDE so I would really like to see which desktop I can open on each screen specifically.

Pagers currently has the option I'm referring too!

**Comment by wsdfhjxc** [comment]
Does KWin provide now separate virtual desktops per monitor? I've always thought virtual desktops are shared across all monitors, i.e. if you switch the current desktop or change the number of desktops, it will affect all monitors. Things might have changed though...

If it's different now, the applet could be fixed. If it's not, I have a hard time imagining how to handle multiple monitors, because shared virtual desktops across all monitors are kind of against the principle of this applet. It never bothered me, because I don't use external monitors, so I'm kind of lost here.
