### ISSUE TITLE
Error loading QML file

### ISSUE THREAD

**Issue by alexrojco** [wsdfhjxc/virtual-desktop-bar#25]
Hey,

I really like the idea of this widget, but I can't get it to work, sadly. I have tried installing, uninstalling many times in all sorts of ways (from the arch AUR, from github and from plasma widget browser) and nothing works.

It always gives me the same error:

`Error loading QML file: file:///usr/local/share/plasma/plasmoids/org.kde.plasma.virtualdesktopbar/contents/ui/Applet.qml:4:1: module "org.kde.plasma.virtualdesktopbar" is not installed. `

I'm running the latest version of EndeavorOS (based on Arch Linux) and the latest kde plasma.

Looking at similar issues #21 , I checked the location of libvirtualdesktopbarplugin.so and it is located under /usr/local/lib/qml/org/kde/plasma/virtualdesktopbar .

Thanks for your work! I'm glad at least some people can appreciate your effort))

Alex

**Comment by wsdfhjxc** [comment]
Eh, that error again...

I think you can try to specify the QML install directory when running CMake.

First, uninstall the applet and remove all files from the `build` directory. Then, do this:

```
cd build
cmake -DQML_INSTALL_DIR=/usr/lib/qt/qml ..
make
sudo make install
```

And restart the panel: `plasmashell --replace & disown`
Or, if you are using Latte: `latte-dock --replace & disown`

**Comment by alexrojco** [comment]
No way, it worked!

Thank you so much for the fast reply!

Your widget is amazing!
Keep up the good work!

**Comment by noersetiawan** [comment]
> Eh, that error again...
> 
> I think you can try to specify the QML install directory when running CMake.
> 
> First, uninstall the applet and remove all files from the `build` directory. Then, do this:
> 
> ```
> cd build
> cmake -DQML_INSTALL_DIR=/usr/lib/qt/qml ..
> make
> sudo make install
> ```
> 
> And restart the panel: `plasmashell --replace & disown`
> Or, if you are using Latte: `latte-dock --replace & disown`

Hello there,

I'm facing this issue as well, but after following your suggestion, I still get the exact same error message.
I have checked #21, and 'libvirtualdesktopbarplugin.so' does exists in '/usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/virtualdesktopbar', before I followed your suggestion.

After uninstalling the applet, these files are gone of course, and since I changed the install directory on CMAKE, now these files are properly installed on `/usr/lib/qt/qml/org/kde/plasma/virtualdesktopbar/`.

Restarted plasma, and the PC, but still the same error message.

I'm using KDE Neon with every updates installed.

Hope my English makes sense, and if you would point me to the right solution, I would really appreciate it. Thanks.

**Comment by wsdfhjxc** [comment]
> I have checked #21, and libvirtualdesktopbarplugin.so does exists in /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/virtualdesktopbar, before I followed your suggestion.

This seems to be a correct location for KDE neon and Ubuntu. It should be fine.

And actually, I've just tried installing the applet on a fresh KDE neon install, and it works correctly, without any errors. I'm really sorry, but I have no idea why it doesn't work in your case.

**Comment by douglastofoli** [comment]
> Eh, that error again...
> 
> I think you can try to specify the QML install directory when running CMake.
> 
> First, uninstall the applet and remove all files from the `build` directory. Then, do this:
> 
> ```
> cd build
> cmake -DQML_INSTALL_DIR=/usr/lib/qt/qml ..
> make
> sudo make install
> ```
> 
> And restart the panel: `plasmashell --replace & disown`
> Or, if you are using Latte: `latte-dock --replace & disown`

Hi. I did it but this problem persists.
`QML: file:///usr/local/share/plasma/plasmoids/org.kde.plasma.virtualdesktopbar/contents/ui/Applet.qml:4:1: module "org.kde.plasma.virtualdesktopbar" is not installed`

**Comment by thiagocarnaes** [comment]
Hi, I had the same problem in Solus.

But the qt folder installation is different from ubuntu, then I change 
cmake -DQML_INSTALL_DIR=/usr/lib/qt/qml ..
to
cmake -DQML_INSTALL_DIR=/usr/lib/qt5/qml ..

and it works

**Comment by Asocia** [comment]
> > I have checked #21, and libvirtualdesktopbarplugin.so does exists in /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/virtualdesktopbar, before I followed your suggestion.
> 
> This seems to be a correct location for KDE neon and Ubuntu. It should be fine.
> 
> And actually, I've just tried installing the applet on a fresh KDE neon install, and it works correctly, without any errors. I'm really sorry, but I have no idea why it doesn't work in your case.

I had the same problem, tried all the solutions on this page and nothing worked. It turns out that I had to restart after installing the plasmoid with default paths. I couldn't execute `plasmashell --replace & disown` because it says "Unknown option 'replace'." 

So that might be the solution for some users, just restart. (logging out and logging in may also work, I don't know how KDE plasma works)

@wsdfhjxc I wanted to thank for all your effort to make this plugin. Keep up the great content!
