### ISSUE TITLE
"sudo make uninstall" fails with an error message

### ISSUE THREAD

**Issue by lyndhurst** [wsdfhjxc/virtual-desktop-bar#39]
Hi,

I am trying to uninstall the widget on an up to date, and clean KDE neon VM. 

The following commands run successfully:

```
git clone https://github.com/wsdfhjxc/virtual-desktop-bar
cd virtual-desktop-bar
./scripts/install-ubuntu-deps.sh -y
mkdir build && cd build
cmake ..
make
```

Then, `sudo make uninstall` returns the following error message:

> Scanning dependencies of target uninstall
> CMake Error at ecm_uninstall.cmake:2 (message):
>  Cannot find install manifest:
>  /home/neon/virtual-desktop-bar/build/install_manifest.txt

> make[3]: *** [CMakeFiles/uninstall.dir/build.make:57: CMakeFiles/uninstall] Error 1
> make[2]: *** [CMakeFiles/Makefile2:309: CMakeFiles/uninstall.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:316: CMakeFiles/uninstall.dir/rule] Error 2
> make: *** [Makefile:279: uninstall] Error 2

Thank you for your time.

**Comment by wsdfhjxc** [comment]
This might sound counter-intuitive, but you first need to do `sudo make install` and then you'll be able to cleanly do `sudo make uninstall`. That's because `make` needs to know about all of the installed files, and `sudo make install` generates some hints. If the hints are missing, `make` is clueless and unable to remove these files. It's a side-effect of installing software from source.

**Comment by lyndhurst** [comment]
Thanks for taking the time to explain that in details. Even if it is counter-intuitive as you pointed, it does make sense now.
I am trying to build a script to automate the installation of all my favorites KDE applications and widgets, so, I am sure this piece of knowledge is gonna be useful more than once.
Thanks again.
