### ISSUE TITLE
Deleting a virtual desktop doesn't reflected to plasmoid

### ISSUE THREAD

**Issue by Asocia** [wsdfhjxc/virtual-desktop-bar#44]
![smaller](https://user-images.githubusercontent.com/32161460/99910560-c21e9980-2cff-11eb-8bf3-45452eeebc32.gif)
Above one is Virtual Desktop Bar and the below one is default Pager plasmoid.
My environment:

- OS: Ubuntu 18.04
- DE: Kubuntu 18.04
- KDE Plasma Version: 5.12.9
- KDE Frameworks Version: 5.44.0
- Qt Version: 5.9.5

**Comment by wsdfhjxc** [comment]
I can't reproduce it. Does it also happen when the applet is placed directly in a panel, instead of being a desktop widget? To be honest, the plasmoid is primarily intended to be used inside a panel, but it definitely shouldn't display removed desktops...

Also, could you try this in the terminal?

```
plasmashell -d --replace & disown
```

This will restart the Plasma desktop and start printing logged debug information in the terminal.
Now, when you remove a desktop through the plasmoid, does any QML-related error appear in the log afterwards? 

By the way, thanks for the effort of recording a preview GIF, I appreciate that. And I'm sorry that you've been encountering numerous problems with the applet, one after another. But it's been a while since I last used Kubuntu 18.04, and maybe that issue is directly related to older Qt or KDE Frameworks versions, as I can't reproduce the issue on latest 20.04 LTS.

**Comment by Asocia** [comment]
- It also happens when I put it to the panel. 
- I can't try `plasmashell` command but I really want. When I try it, it says `Unknown option 'replace'.` probably because I have an old version of it. (`plasmashell 5.12.9`)

As you have already mentioned, most of the issues I'm facing are related with older versions of programs that I'm using. Maybe it's time to upgrade my system :) But I have so many configurations currently and I'm afraid to do it. 

> ... start printing logged debug information in the terminal.

I can provide this information if you are interested and tell me a way to do it but I'm not going to leave this issue open because the problem is on my side. Thanks for all the effort!

**Comment by wsdfhjxc** [comment]
Ok, since the `--replace` option is unavailable, you can do this:

```
killall plasmashell; plasmashell -d & disown
```

Then clear the terminal contents (Ctrl+L) and clear scrollback (option in the right-click menu). Once the terminal is more or less empty, try to remove a desktop in the same way as you did earlier. If, for some reason, there's still too much information noise in the terminal, you can press Ctrl+Shift+F and search for `virtualdesktopbar`, so it's easier to recognize QML-related errors.

**Comment by Asocia** [comment]
I didn't get any errors when I remove it. There is nothing related with `virtualdesktopbar` in the output at all.

**Comment by wsdfhjxc** [comment]
Thanks for the report, it seems quite weird. In that case, I'll spin a Kubuntu 18.04 virtual machine and try to address the issue.

**Comment by wsdfhjxc** [comment]
Ok, I think it's been fixed.

**Comment by Asocia** [comment]
Yeah, you're amazing!
