### ISSUE TITLE
Add/Remove desktop greyed out

### ISSUE THREAD

**Issue by Dhamma-valence** [wsdfhjxc/virtual-desktop-bar#55]
I'm using this on Debian Testing and latte-dock. For some reason the buttons `Remove Desktop` `Add Desktop` and `Remove Last Desktop` are greyed out and unusable. I just made sure it was updated to latest and reinstalled it, but no change.

**Comment by wsdfhjxc** [comment]
Is the "Enable dynamic desktops" option in preferences checked?

**Comment by Dhamma-valence** [comment]
Oh wow. Yes it is, and unchecking it fixed it. Thanks, I'm glad the solution was so simple.

**Comment by wsdfhjxc** [comment]
Yeah, when the dynamic mode is enabled, desktops are added and removed automatically, and that's why manual actions are disabled. It's done on purpose. And actually, there are hint icons next to disabled controls with some additional information, but maybe they couldn't be visible due to some theming issues, e.g. white icons on a white background (Breeze Twilight).
